#!/usr/bin/env bash
# Builds every artifact attached to a Cullr GitHub release:
#
#   dist/cullr_<ver>-1_amd64.deb            Debian/Ubuntu  (apt install ./…)
#   dist/cullr-<ver>-1.x86_64.rpm           Fedora/RHEL    (dnf install ./…)
#   dist/cullr-<ver>-1-x86_64.pkg.tar.zst   Arch Linux     (pacman -U ./…)
#   dist/cullr-<ver>-x86_64-linux.tar.gz    portable tarball
#
# Prerequisites: cargo, dpkg-deb, cargo-generate-rpm (`cargo install
# cargo-generate-rpm`), zstd. Runs anywhere those exist — including the
# GitHub release workflow, where the pacman package's absence of any
# pacman dependency is exactly what makes it buildable. Pass --no-build
# to reuse the existing target/release/cullr-ui.
set -euo pipefail

cd "$(dirname "$0")/.."

version=$(sed -n 's/^version = "\(.*\)"$/\1/p' Cargo.toml | head -n1)
if [ -z "$version" ]; then
    echo "error: cannot read workspace version from Cargo.toml" >&2
    exit 1
fi

if [ "${1:-}" != "--no-build" ]; then
    cargo build --release -p cullr-ui
fi

binary=target/release/cullr-ui
mkdir -p dist

# Source date epoch: the HEAD commit timestamp stamps every packaged file,
# so rebuilding the same commit yields byte-identical archives.
epoch=$(git log -1 --format=%ct)
tmp=$(mktemp -d)
trap 'rm -rf "$tmp"' EXIT

echo "==> cullr $version (epoch $epoch)"

# --- deb ------------------------------------------------------------------
deb="$tmp/deb"
install -Dm755 "$binary" "$deb/usr/bin/cullr-ui"
install -Dm644 LICENSE "$deb/usr/share/doc/cullr/copyright"
kib=$(du -sk "$deb/usr" | cut -f1)
mkdir -p "$deb/DEBIAN"
cat > "$deb/DEBIAN/control" <<EOF
Package: cullr
Version: ${version}-1
Section: graphics
Priority: optional
Architecture: amd64
Installed-Size: ${kib}
Depends: libc6 (>= 2.39), libgcc-s1, libgtk-3-0, libx11-6, libxcursor1, libxrandr2, libxi6, libxkbcommon0, libxkbcommon-x11-0, libwayland-client0, libgl1
Maintainer: Sikander Khan <skhan1903@outlook.com>
Homepage: https://github.com/SikKhan/Cullr
Description: Photo Mechanic-style culling tool for RAW photographs
 Cullr opens a folder of RAW photos and shows their embedded JPEG
 previews instantly: virtualized contact sheet, full-screen loupe,
 color labels, filtering, and export of the originals you keep.
 Keyboard-first; runs on X11 and Wayland.
EOF
dpkg-deb --build --root-owner-group "$deb" "dist/cullr_${version}-1_amd64.deb"

# --- rpm ------------------------------------------------------------------
command -v cargo-generate-rpm >/dev/null || {
    echo "error: cargo-generate-rpm missing (cargo install cargo-generate-rpm)" >&2
    exit 1
}
# Asset paths in [package.metadata.generate-rpm] are resolved against the
# current directory, so this must run from the crate dir (hence the
# ../../ prefixes there).
(cd crates/cullr-ui && cargo generate-rpm)
mv crates/cullr-ui/target/generate-rpm/cullr-*.rpm "dist/"
rm -rf crates/cullr-ui/target

# --- Arch Linux -------------------------------------------------------------
pkg="$tmp/pkg"
install -Dm755 "$binary" "$pkg/usr/bin/cullr-ui"
install -Dm644 LICENSE "$pkg/usr/share/licenses/cullr/LICENSE"
size=$(du -sb "$pkg/usr" | cut -f1)

cat > "$pkg/.PKGINFO" <<EOF
pkgname = cullr
pkgver = ${version}-1
pkgdesc = Photo Mechanic-style culling tool for RAW photographs
url = https://github.com/SikKhan/Cullr
builddate = ${epoch}
packager = Sikander Khan <skhan1903@outlook.com>
size = ${size}
arch = x86_64
license = GPL-3.0-or-later
depend = glibc
depend = gcc-libs
depend = gtk3
depend = libx11
depend = libxcursor
depend = libxrandr
depend = libxi
depend = libxkbcommon
depend = libxkbcommon-x11
depend = wayland
depend = mesa
EOF

# .MTREE lists every payload path with mode/uid/gid/digests so pacman can
# verify the package; it lives inside the archive as a gzipped stream and
# never lists itself or .PKGINFO.
{
    echo "#Generated by cullr packaging"
    (
        cd "$pkg"
        find usr -mindepth 1 | LC_ALL=C sort | while read -r path; do
            if [ -d "$path" ]; then
                printf '%s set type=dir mode=755 uid=0 gid=0 time=%s.0\n' \
                    "$path" "$epoch"
            else
                printf '%s set type=file mode=%s uid=0 gid=0 size=%s md5digest=%s sha256digest=%s time=%s.0\n' \
                    "$path" "$(stat -c %a "$path")" "$(stat -c %s "$path")" \
                    "$(md5sum "$path" | cut -d' ' -f1)" \
                    "$(sha256sum "$path" | cut -d' ' -f1)" "$epoch"
            fi
        done
    )
} | gzip -n > "$pkg/.MTREE"

tar --zstd -cf "dist/cullr-${version}-1-x86_64.pkg.tar.zst" \
    --sort=name --mtime="@${epoch}" --owner=0 --group=0 --numeric-owner \
    -C "$pkg" .PKGINFO .MTREE usr

# --- portable tarball --------------------------------------------------------
# Standalone binary for distros without a matching package; same layout as
# the packages minus installation.
tar -cf - -C target/release --sort=name --mtime="@${epoch}" \
    --owner=0 --group=0 --numeric-owner cullr-ui \
    | gzip -n > "dist/cullr-${version}-x86_64-linux.tar.gz"

echo "==> artifacts:"
ls -lh dist/cullr_*.deb dist/cullr-*.rpm dist/cullr-*.pkg.tar.zst \
    dist/cullr-*.tar.gz
